apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: doz23/disney-producer:latest
        env:
        - name: RABBITMQ_HOST
          value: rabbitmq.rabbitmq.svc.cluster.local
        - name: RABBITMQ_USER
          value: disney
        - name: RABBITMQ_PASS
          value: magicpass