apiVersion: v1
kind: Service
metadata:
  name: producer-service
spec:
  selector:
    app: producer
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000   # Adjust if your app uses a different port
      nodePort: 30080    # Exposed port on each node